version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    reviewers:
      - "tstangenberg"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
    reviewers:
      - "tstangenberg"
